# GLOBAL SITE SETTINGS

cname: hocw.yourwebvisual.com

# General
seo_title:
title: "Hicks Oakley Chessell Williams Lawyers & Notary"
short_title: hocw
company: "Hicks Oakley Chessell Williams Lawyers & Notary"
description: ""
email: enquiries@hocw.com.au

author_site: http://www.muchmedia.com.au

offices:
  - title: Melbourne
    address: "Level 13<br> 379 Collins Street<br> Melbourne Victoria 3000"
    phone: 03 9629 7411
    fax: 03 9629 7422
    DX: "31331 Mid-town <br>PO Box 446, Flinders Lane<br> Melbourne VIC 8009"

  - title: Mount Waverley
    address: "Level 13<br> 379 Collins Street<br> Melbourne Victoria 3000"
    phone: 03 9550 4600
    fax: 03 9629 7422
    DX: "31331 Mid-town <br>PO Box 446, Flinders Lane<br> Melbourne VIC 8009"

# Contact Info
email: test@email.com

# Social Networks
facebook:
linked_in:
google_plus:

# Google Map
google_map: ""

# Google Analytics
google_analytics: ""

# Breakpoints
breakpoints:
  small  : 640
  medium : 768
  large  : 1024
  xlarge : 1170
  #previously: 1250
  xxlarge: 1400